redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/admirdemir/Projects/sabrinacaber-com-astro/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/fr"
to = "/fr/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]